### ISSUE TITLE
Code Review for Setting the Kanban Board at Space Travelers Hub Project

### ISSUE THREAD

**Issue by luigirazum** [luigirazum/mv-space-travelers-app#25]
# Hello Dear Code Reviewers Team 👋,
### The following requirements 📌 were fulfilled this time:
- 📌 Set up the Kanban board
    - ✅ Done. The link for the project is 👉 [https://github.com/luigirazum/mv-space-travelers-app](https://github.com/luigirazum/mv-space-travelers-app)

## ❗ I've been working solo since the past week, so I don't have a "Team".
- 📌 I assigned the tasks for two people team, but if I need to, I can modify to just one person, and delete the resto of the cards.
- 📌 Here 👇 is the email which I got the approval to continue the Microverse program in "solo".
    ![working_solo_email](https://user-images.githubusercontent.com/67355479/218551781-59e540f0-f6c5-49e5-8d5a-87aeb0904c24.png)

### Luis 🙋‍♂️

**Comment by luigirazum** [comment]
Thanks @Qoosim, I'll try my best to complete it as if we were two.... by the way, I would like to ask you a big favor... Would you mind to give me the Code Reviews as if you were my Coding Partner? I know it's a lot to ask...

Thanks again!!

**Comment by Qoosim** [comment]
@luigirazum you're most welcome. Let's see how it goes. Let me know anytime you need my attention regarding the request. :heart:

**Comment by luigirazum** [comment]
Yay!!! Thanks again @Qoosim.
I'll let you know.
